### PR TITLE
Ob 338 fulfillment info Part 1

### PR DESCRIPTION
**Pull request by charleskoehl**
I still have more work to do on this for OB-338, but I'm creating this PR now so it doesn't get too big (@rizowski).

In this PR, you can select check-in, check-out times, enter info for the initial, non-deletable check-in policy, and add / trash additional policies.

### CODE REVIEW

**Comment by JasonTowner** [comment]
Nice work!

**Comment by JasonTowner** [comment]
Make sure to make the input fields for `instructions` and `addendum` text areas instead of regular text input

**Comment by charleskoehl** [comment]
@JasonTowner the input fields for instructions and addendum are actually iron-autogrow-textarea's but they refuse to grow

**Comment by JasonTowner** [comment]
interesting. We'll have to play with it. thanks

**Pull request merged**
