### PR TITLE
Sort policies by start-date, keeping ones with empty dates at top

### PR DESCRIPTION
**Pull request by charleskoehl**

### CODE REVIEW

**Comment by PoetsRock** [comment]
hey @charleskoehl  ... i'm getting some console errors...

 when i load the demo:

```
GET http://localhost:3036/components/moment/min/moment.js 
check-in-policies.html:174 Uncaught SyntaxError: Unexpected identifier
```

and, when i click on the `+ NEW SEASONAL CHECK-IN POLICY`button:
`Uncaught TypeError: this.$.checkInPolicies.lcbAdd is not a function`

**Comment by charleskoehl** [comment]
Are you sure you bower installed fully?

Sent by Outlookhttp://taps.io/outlookmobile for Android

On Thu, Nov 12, 2015 at 3:17 PM -0800, "Chris Tanseer" <notifications@github.com<mailto:notifications@github.com>> wrote:

hey @charleskoehlhttps://github.com/charleskoehl ... i'm getting some console errors...

when i load the demo:

GET http://localhost:3036/components/moment/min/moment.js
check-in-policies.html:174 Uncaught SyntaxError: Unexpected identifier

and, when i click on the + NEW SEASONAL CHECK-IN POLICYbutton:
Uncaught TypeError: this.$.checkInPolicies.lcbAdd is not a function

##

**Comment by charleskoehl** [comment]
Nevermind. It's missing a comma after the behaviors. I was staging lines instead of chunks and missed it. I'll push the fix in 30 minutes or so

**Comment by PoetsRock** [comment]
yeah, i updated a few times .... 

i'm guessing the error with moment is just a missing dependency in one of the polymer element's `bower.json` file? ... probably for one of the time/date picker sub-components?  maybe it works for you bc it's on your local machine but forgot the `--save` when installing?

and, i can't find where `checkInPolicies.lcbAdd()` is defined... so, i'm assuming that's why i'm getting the error when clicking that button.

(Also, what does "lcb" stand for? is there a name that's more readable?)

**Comment by PoetsRock** [comment]
cool... yeah, that comma looks like it took care of most of the issues ... 

do you know where that moment.js dependency error is coming from? this is the only issue i see that's left.

**Comment by charleskoehl** [comment]
@PoetsRock: "lcb" stands for LeisureLink Collection Behavior and is for namespacing each method of the behavior. Perhaps we need to define a naming convention for namespacing the methods added by ll behaviors?

**Comment by charleskoehl** [comment]
@PoetsRock as I am still working on other aspects of ll-property-information, I think we should ignore those js errors and just merge this sorting functionality for now.

**Comment by charleskoehl** [comment]
I have verified that those javascript errors only happen in the demo. They do not happen when ll-property-information is used inside IH.

**Pull request closed without merging**
